# mihomo (Clash Meta) é…ç½®
# è™šç©ºç»ˆç«¯ (Clash Meta) Docs åœ°å€: https://wiki.metacubex.one


# ---------------------------------------------------
## å…¨å±€é…ç½®

# è¿è¡Œæ¨¡å¼
# rule: è§„åˆ™
# global: å…¨å±€
# direct: å…¨å±€ç›´è¿
mode: rule
# ipv6 æ”¯æŒ
ipv6: true
# æ—¥å¿—è®°å½•çº§åˆ«: silent, debug, info, warning, error
log-level: info
# å…è®¸å±€åŸŸç½‘è¿æ¥
allow-lan: true
# socks5/http ç«¯å£
mixed-port: 7890
# é€æ˜ä»£ç†ç«¯å£
redir-port: 7893
tproxy-port: 7894
# adnroid
# tproxy-port: 1536
# Meta å†…æ ¸ç‰¹æ€§ https://wiki.metacubex.one/config/general
# ç»Ÿä¸€å»¶è¿Ÿ
# æ›´æ¢å»¶è¿Ÿè®¡ç®—æ–¹å¼,å»é™¤æ¡æ‰‹ç­‰é¢å¤–å»¶è¿Ÿ
unified-delay: true
# TCP å¹¶å‘
# åŒæ—¶å¯¹æ‰€æœ‰ipè¿›è¡Œè¿æ¥ï¼Œè¿”å›å»¶è¿Ÿæœ€ä½çš„åœ°å€
tcp-concurrent: true
# å¤–éƒ¨æ§åˆ¶ç«¯å£
external-controller: 127.0.0.1:9090
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
external-ui: ./dashbord/Zash/
secret: "" # é¢æ¿è®¿é—®å¯†ç 
# geoæ–‡ä»¶ä½¿ç”¨æ¨¡å¼ true -> dat, false -> mmdb
geodata-mode: true
geo-auto-update: true
geo-update-interval: 48
# Geo æ•°æ®åº“ä¸‹è½½åœ°å€
# æºåœ°å€ https://github.com/MetaCubeX/meta-rules-dat
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

# è¿›ç¨‹åŒ¹é…æ¨¡å¼
# è·¯ç”±å™¨ä¸Šè¯·è®¾ç½®ä¸º off
# always å¼€å¯ï¼Œå¼ºåˆ¶åŒ¹é…æ‰€æœ‰è¿›ç¨‹
# strict é»˜è®¤ï¼Œç”± Clash åˆ¤æ–­æ˜¯å¦å¼€å¯
# off ä¸åŒ¹é…è¿›ç¨‹ï¼Œæ¨èåœ¨è·¯ç”±å™¨ä¸Šä½¿ç”¨æ­¤æ¨¡å¼
find-process-mode: strict

# ç¼“è§£ç§»åŠ¨è®¾å¤‡è€—ç”µé—®é¢˜
# https://github.com/vernesong/OpenClash/issues/2614
keep-alive-interval: 1800

# å…¨å±€å®¢æˆ·ç«¯æŒ‡çº¹
global-client-fingerprint: random # éšæœºæŒ‡çº¹

# ç¼“å­˜
profile:
  store-selected: true
  store-fake-ip: true

# è‡ªåŠ¨åŒæ­¥æ—¶é—´ä»¥é˜²æ­¢æ—¶é—´ä¸å‡†å¯¼è‡´æ— æ³•æ­£å¸¸è”ç½‘
ntp:
  enable: true
  # æ˜¯å¦åŒæ­¥è‡³ç³»ç»Ÿæ—¶é—´ï¼Œéœ€è¦ root/ç®¡ç†å‘˜æƒé™
  write-to-system: false
  server: time.apple.com
  port: 123
  interval: 30

# --------------------------------------------------
## åˆ†ç»„

pr:
  &pr {
    type: select,
    proxies:
      [
        èŠ‚ç‚¹é€‰æ‹©,
        è‡ªåŠ¨é€‰æ‹©,
        DIRECT,
        é¦™æ¸¯,
        å°æ¹¾,
        æ—¥æœ¬,
        æ–°åŠ å¡,
        ç¾å›½,
        å…¶å®ƒåœ°åŒº,
      ],
  }
# å»¶è¿Ÿæ£€æµ‹ URL
p: &p
  # http/file/inline
  type: http
  # è‡ªåŠ¨æ›´æ–°è®¢é˜…æ—¶é—´ï¼Œå•ä½ä¸ºç§’
  interval: 3600
  health-check:
    enable: true
    url: https://cp.cloudflare.com
    # èŠ‚ç‚¹è¿é€šæ€§æ£€æµ‹æ—¶é—´ï¼Œå•ä½ä¸ºç§’
    interval: 300
    # èŠ‚ç‚¹è¶…æ—¶å»¶è¿Ÿï¼Œå•ä½ä¸ºæ¯«ç§’
    timeout: 1000
    # èŠ‚ç‚¹è‡ªåŠ¨åˆ‡æ¢å·®å€¼ï¼Œå•ä½ä¸ºæ¯«ç§’
    tolerance: 100


# ä½¿ç”¨çš„è®¢é˜…
use: &use
  # å¦‚æœä¸å¸Œæœ›è‡ªåŠ¨åˆ‡æ¢è¯·å°†ä¸‹é¢ä¸¤è¡Œæ³¨é‡Šå¯¹è°ƒ
  type: select
  # type: url-test
  use:
    - sub1
    # - local

# ä»£ç†é›†åˆ
# å¯¹äºè®¢é˜…æ¥è¯´ï¼Œpath ä¸ºé€‰å¡«é¡¹ï¼Œä½†å»ºè®®å¯ç”¨
# æœ¬åœ°é…ç½®å¯ä»¥åªå¡« path
proxy-providers:
  sub1:
    <<: *p
    type: http
    path: ./proxy_provider/sub1.yaml
    url: ""
    # å¦‚éœ€è¦ä¸ºè¯¥è®¢é˜…ç»„èŠ‚ç‚¹æ·»åŠ å‰ç¼€ï¼Œå–æ¶ˆä¸‹é¢ä¸¤è¡Œæ³¨é‡Š
    # override:
      # additional-prefix: "[è®¢é˜…ä¸€]"

    # å¦‚éœ€è¦ä¸ºè¯¥è®¢é˜…ç»„èŠ‚ç‚¹æ·»åŠ å‰ç¼€ï¼Œå–æ¶ˆä¸‹é¢ä¸¤è¡Œæ³¨é‡Š
    # override:
      # additional-prefix: "[è®¢é˜…äºŒ]"

  # local:
    # <<: *p
    # type: file
    # path: ./proxy_provider/æœ¬åœ°é…ç½®.yaml
    # å¦‚éœ€è¦ä¸ºè¯¥è®¢é˜…ç»„èŠ‚ç‚¹æ·»åŠ å‰ç¼€ï¼Œå–æ¶ˆä¸‹é¢ä¸¤è¡Œæ³¨é‡Š
    # override:
      # additional-prefix: "[æœ¬åœ°é…ç½®]"

# ---------------------------------------------
## dns è®¾ç½®

# å·²é…ç½® ipv6
dns:
  enable: true
  listen: :1053
  ipv6: true
  # è·¯ç”±å™¨ä¸ªäººå»ºè®®ä½¿ç”¨ redir-host ä»¥æœ€ä½³å…¼å®¹æ€§
  # å…¶ä»–è®¾å¤‡å¯ä»¥ä½¿ç”¨ fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - '[2402:4e00::]'
    - '[2400:3200::1]'
  nameserver:
    - 'tls://8.8.4.4#dns'
    - 'tls://1.0.0.1#dns'
    - 'tls://[2001:4860:4860::8844]#dns'
    - 'tls://[2606:4700:4700::1001]#dns'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:!cn,!private": 
      - "tls://dns.google"
      - "tls://cloudflare-dns.com"

# åŸŸåå—…æ¢
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

# tun æ¨¡å¼
tun:
  enable: false  # enable 'true'
  # tunæ¨¡å¼å †æ ˆï¼Œå¯é€‰ system, gvisor, mixed(æ¨è)
  # è‹¥å¼€å¯é˜²ç«å¢™ï¼Œåˆ™éœ€è¦æ”¾è¡Œclashæˆ–è€…ä¸ä½¿ç”¨system/mixed
  stack: mixed
  device: utun_clash
  # dnsåŠ«æŒï¼Œwindows/macosæ— æ³•è‡ªåŠ¨åŠ«æŒåˆ°å±€åŸŸç½‘dnsè¯·æ±‚ï¼Œandroidåœ¨å¼€å¯ç§äººdnsåæ— æ³•è‡ªåŠ¨åŠ«æŒdnsè¯·æ±‚
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  # è‡ªåŠ¨è®¾ç½®å…¨å±€è·¯ç”±æµé‡åˆ°tun
  auto-route: true
  # è‡ªåŠ¨é€‰æ‹©å‡ºå£ç½‘å¡æ¥å£
  auto-detect-interface: true


## WRAPä»£ç†è®¾ç½®
# proxies:
  # - name: "WARP"
  #   type: wireguard
  #   server: engage.cloudflareclient.com
  #   port: 2408
  #   ip: "172.16.0.2/32"
  #   ipv6: "2606::1/128"        # è‡ªè¡Œæ›¿æ¢
  #   private-key: "private-key" # è‡ªè¡Œæ›¿æ¢
  #   public-key: "public-key"   # è‡ªè¡Œæ›¿æ¢
  #   udp: true
  #   reserved: "abba"           # è‡ªè¡Œæ›¿æ¢
  #   mtu: 1280
  #   dialer-proxy: "WARPå‰ç½®"
  #   remote-dns-resolve: true
  #   dns:
  #     - https://dns.cloudflare.com/dns-query

# ä»£ç†ç»„
proxy-groups:
  # ä½¿ç”¨ WARP éœ€è¦æ‰‹åŠ¨åœ¨ä¸‹æ–¹çš„ proxies å­—æ®µå†…æ·»åŠ  WARP
  # ä¾‹å¦‚ [WARP, å…¨éƒ¨èŠ‚ç‚¹, è‡ªåŠ¨é€‰æ‹©, é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, å…¶å®ƒåœ°åŒº, DIRECT],
  - {
      name: èŠ‚ç‚¹é€‰æ‹©,
      type: select,
      proxies:
        [å…¨éƒ¨èŠ‚ç‚¹, è‡ªåŠ¨é€‰æ‹©, DIRECT,é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, å…¶å®ƒåœ°åŒº],
    }
  - { name: å…¨éƒ¨èŠ‚ç‚¹, <<: *use }
  - { name: è‡ªåŠ¨é€‰æ‹©, <<: *use, tolerance: 2, type: url-test }
  # è¿™é‡Œçš„ dns æŒ‡æµ·å¤–è§£æ dns èµ°çš„èŠ‚ç‚¹ï¼Œä¸€èˆ¬è·ŸéšèŠ‚ç‚¹é€‰æ‹©å³å¯
  - { name: dns, <<: *pr }
  # WARP é…ç½®é“¾å¼å‡ºç«™
  # - { name: WARPå‰ç½®, <<: *pr, exclude-type: "wireguard" }

  - { name: å¹¿å‘Šæ‹¦æˆª, type: select, proxies: [REJECT, DIRECT, èŠ‚ç‚¹é€‰æ‹©] }
  - { name: AIæœåŠ¡, <<: *pr }
  # Apple æ¨èèµ°å…¨å±€ç›´è¿
  - { name: Apple, <<: *pr }
  - { name: Google, <<: *pr }
  - { name: Telegram, <<: *pr }
  - { name: Twitter, <<: *pr }
  - { name: Pixiv, <<: *pr }
  - { name: ehentai, <<: *pr }
  - { name: YouTube, <<: *pr }
  - { name: Netflix, <<: *pr }
  - { name: TikTok, <<: *pr }
  - { name: Spotify, <<: *pr }
  - { name: Github, <<: *pr }
  - { name: Steam, <<: *pr }
  - { name: OneDrive, <<: *pr }
  - { name: å¾®è½¯æœåŠ¡, <<: *pr }
  - {
      name: å›½å†…,
      type: select,
      proxies:
        [
          DIRECT,
          èŠ‚ç‚¹é€‰æ‹©,
          å…¨éƒ¨èŠ‚ç‚¹,
          è‡ªåŠ¨é€‰æ‹©,
          é¦™æ¸¯,
          å°æ¹¾,
          æ—¥æœ¬,
          æ–°åŠ å¡,
          ç¾å›½,
          å…¶å®ƒåœ°åŒº,
        ],
    }
  # å…¶ä»–å°±æ˜¯æ‰€æœ‰è§„åˆ™æ²¡åŒ¹é…åˆ°çš„
  # å¯ä»¥ç†è§£ä¸º ACL4SSR é…ç½®é‡Œçš„ æ¼ç½‘ä¹‹é±¼
  # æ¢è¨€ä¹‹ï¼Œå…¶ä»–èµ°ä»£ç†å°±æ˜¯ç»•è¿‡ä¸­å›½å¤§é™†åœ°å€ï¼Œä¸èµ°å°±æ˜¯ GFWList æ¨¡å¼
  - { name: æ¼ç½‘ä¹‹é±¼, <<: *pr }
  # åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - { name: é¦™æ¸¯, <<: *use, filter: "(?i)æ¸¯|hk|hongkong|hong kong" }
  - { name: å°æ¹¾, <<: *use, filter: "(?i)å°|tw|taiwan" }
  - { name: æ—¥æœ¬, <<: *use, filter: "(?i)æ—¥æœ¬|jp|japan" }
  - { name: ç¾å›½, <<: *use, filter: "(?i)ç¾|us|unitedstates|united states" }
  - { name: æ–°åŠ å¡, <<: *use, filter: "(?i)(æ–°|sg|singapore)" }
  - {
      name: å…¶å®ƒåœ°åŒº,
      <<: *use,
      filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*",
    }

# è§„åˆ™è®¢é˜…
rule-providers:
  # ç§‹é£å¹¿å‘Šæ‹¦æˆªè§„åˆ™
  # https://awavenue.top
  # ç”±äº Anti-AD è¯¯æ€ç‡é«˜ï¼Œæœ¬é¡¹ç›®å·²åœ¨ 1.11-241024 ç‰ˆæœ¬æ›´æ¢ç§‹é£å¹¿å‘Šè§„åˆ™
  AWAvenue-Ads:
    type: http
    behavior: domain
    format: yaml
    # pathå¯ä¸ºç©º(ä»…é™clash.meta 1.15.0ä»¥ä¸Šç‰ˆæœ¬)
    path: ./rule_provider/AWAvenue-Ads.yaml
    url: "https://gcore.jsdelivr.net/gh/TG-Twilight/AWAvenue-Ads-Rule@main/Filters/AWAvenue-Ads-Rule-Clash.yaml"
    interval: 600

rules:
  # è‹¥éœ€ç¦ç”¨ QUIC è¯·å–æ¶ˆæ³¨é‡Š QUIC ä¸¤æ¡è§„åˆ™
  # é˜²æ­¢ YouTube ç­‰ä½¿ç”¨ QUIC å¯¼è‡´é€Ÿåº¦ä¸ä½³, ç¦ç”¨ 443 ç«¯å£ UDP æµé‡ï¼ˆä¸åŒ…æ‹¬å›½å†…ï¼‰
# - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT
# - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT
  - RULE-SET,AWAvenue-Ads,å¹¿å‘Šæ‹¦æˆª
  - GEOSITE,category-ai-chat-!cn,AIæœåŠ¡
  - GEOSITE,apple,Apple
  - GEOSITE,apple-cn,Apple
  - GEOSITE,ehentai,ehentai
  - GEOSITE,github,Github
  - GEOSITE,twitter,Twitter
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,google-cn,Google # Google CN ä¸èµ°ä»£ç†ä¼šå¯¼è‡´é¦™æ¸¯ç­‰åœ°åŒºèŠ‚ç‚¹ Play Store å¼‚å¸¸
  - GEOSITE,telegram,Telegram
  - GEOSITE,netflix,Netflix
  - GEOSITE,tiktok,TikTok
  - GEOSITE,spotify,Spotify
  - GEOSITE,pixiv,Pixiv
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,steam,Steam
  - GEOSITE,onedrive,OneDrive
  - GEOSITE,microsoft,å¾®è½¯æœåŠ¡
  - GEOSITE,geolocation-!cn,æ¼ç½‘ä¹‹é±¼
  - GEOIP,google,Google
  - GEOIP,netflix,Netflix
  - GEOIP,telegram,Telegram
  - GEOIP,twitter,Twitter
  - GEOSITE,CN,å›½å†…
  - GEOIP,CN,å›½å†…
  # ç»•è¿‡å±€åŸŸç½‘åœ°å€
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - MATCH,æ¼ç½‘ä¹‹é±¼